{
 "title": "L2 Incident Lab",
 "tags": [
  "l2",
  "incident",
  "fastapi"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "requests/s"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_errors_total[1m])) / clamp_min(sum(rate(http_requests_total[1m])), 0.001)",
     "legendFormat": "error rate"
    }
   ]
  },
  {
   "title": "HTTP status codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(http_requests_total[1m]))",
     "legendFormat": "HTTP {{status_code}}"
    }
   ]
  },
  {
   "title": "p95 request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Created orders",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(orders_created_total)", "legendFormat": "orders" }
   ]
  },
  {
   "title": "Current incident mode",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "incident_mode == 1", "legendFormat": "{{mode}}" }
   ]
  }
 ]
}